### ISSUE TITLE
Fails on GitLab when suggesting a changelog entry

### ISSUE THREAD

**Issue by sorenmortensen** [dblock/danger-changelog#34]
Here's the log:

```
$ bundle exec danger --fail-on-errors=true
Passing the note body as a Hash is deprecated.  You should just pass the String.
[!] The exception involves the following plugins:
 -  danger-changelog
bundler: failed to load command: danger (/Users/xxxxx/builds/d9854cfb/0/xxxxx/xxxxx/vendor/bundle/ruby/2.3.0/bin/danger)
Danger::DSLError: 
[!] Invalid `Dangerfile` file: undefined method `github' for #<Danger::Dangerfile:0x00007fdb96ad97a0>
Did you mean?  git
               gitlab
 #  from Dangerfile:6
 #  -------------------------------------------
 #  
 >  changelog.check
 #  -------------------------------------------

  /Users/xxxxx/builds/d9854cfb/0/xxxxx/xxxxx/vendor/bundle/ruby/2.3.0/gems/danger-5.6.4/lib/danger/danger_core/dangerfile.rb:69:in `method_missing'
  /Users/xxxxx/builds/d9854cfb/0/xxxxx/xxxxx/vendor/bundle/ruby/2.3.0/gems/danger-5.6.4/lib/danger/plugin_support/plugin.rb:23:in `method_missing'
  /Users/xxxxx/builds/d9854cfb/0/xxxxx/xxxxx/vendor/bundle/ruby/2.3.0/gems/danger-changelog-0.3.0/lib/changelog/plugin.rb:51:in `have_you_updated_changelog?'
  /Users/xxxxx/builds/d9854cfb/0/xxxxx/xxxxx/vendor/bundle/ruby/2.3.0/gems/danger-changelog-0.3.0/lib/changelog/plugin.rb:31:in `check'
  Dangerfile:6:in `block in parse'
  /Users/xxxxx/builds/d9854cfb/0/xxxxx/xxxxx/vendor/bundle/ruby/2.3.0/gems/danger-5.6.4/lib/danger/danger_core/dangerfile.rb:200:in `eval'
  /Users/xxxxx/builds/d9854cfb/0/xxxxx/xxxxx/vendor/bundle/ruby/2.3.0/gems/danger-5.6.4/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
  /Users/xxxxx/builds/d9854cfb/0/xxxxx/xxxxx/vendor/bundle/ruby/2.3.0/gems/danger-5.6.4/lib/danger/danger_core/dangerfile.rb:196:in `instance_eval'
  /Users/xxxxx/builds/d9854cfb/0/xxxxx/xxxxx/vendor/bundle/ruby/2.3.0/gems/danger-5.6.4/lib/danger/danger_core/dangerfile.rb:196:in `parse'
  /Users/xxxxx/builds/d9854cfb/0/xxxxx/xxxxx/vendor/bundle/ruby/2.3.0/gems/danger-5.6.4/lib/danger/danger_core/dangerfile.rb:274:in `run'
  /Users/xxxxx/builds/d9854cfb/0/xxxxx/xxxxx/vendor/bundle/ruby/2.3.0/gems/danger-5.6.4/lib/danger/danger_core/executor.rb:28:in `run'
  /Users/xxxxx/builds/d9854cfb/0/xxxxx/xxxxx/vendor/bundle/ruby/2.3.0/gems/danger-5.6.4/lib/danger/commands/runner.rb:68:in `run'
  /Users/xxxxx/builds/d9854cfb/0/xxxxx/xxxxx/vendor/bundle/ruby/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /Users/xxxxx/builds/d9854cfb/0/xxxxx/xxxxx/vendor/bundle/ruby/2.3.0/gems/danger-5.6.4/bin/danger:5:in `<top (required)>'
  /Users/xxxxx/builds/d9854cfb/0/xxxxx/xxxxx/vendor/bundle/ruby/2.3.0/bin/danger:23:in `load'
  /Users/xxxxx/builds/d9854cfb/0/xxxxx/xxxxx/vendor/bundle/ruby/2.3.0/bin/danger:23:in `<top (required)>'
ERROR: Job failed: exit status 1
```

**Comment by dblock** [comment]
Never tried this on Gitlab. Would definitely take pull requests for gitlab support!

**Comment by MateuszFilipekX** [comment]
Bumping the new feature

**Comment by dblock** [comment]
Please contribute @MateuszFilipekX !
